remote_theme: jekyll/minima
minima:
  skin: auto
  hide_site_feed_link: true
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/simontreanor"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/simontreanor/"
    - title: Bluesky
      icon: bluesky
      url: "https://bsky.app/profile/simontreanor.bsky.social"
plugins:
- jekyll-remote-theme
